#!/bin/bash
set -euo pipefail

# Task 001: Apply Cybersecurity Framework
# This script must be run manually before Ralph can execute this task
# Generated by: lib/generate_task_scripts.sh

echo "🔧 Setting up prerequisites for Task 001: Apply Cybersecurity Framework"
echo ""

# Commands from @fix_plan.md Steps section
cd /home/dev/Development/cyberSecurity
./INSTALL_ALL_SECURITY_TOOLS.sh
./SETUP_PROJECT_HOOKS.sh irStudy
cd /home/dev/Development/irStudy
pre-commit run --all-files
echo ""
echo "✅ Prerequisite script completed"
echo ""

# Run verification if available
if [[ -f "tasks/001/verify.sh" ]]; then
    echo "🔍 Running verification checks..."
    bash tasks/001/verify.sh
else
    echo "ℹ️  No verification script found (tasks/001/verify.sh)"
fi
