#!/bin/bash
# Export Firefox cookies for Cochrane Library
# This script helps you export cookies manually

echo "=================================================="
echo "Firefox Cookie Export Instructions"
echo "=================================================="
echo ""
echo "METHOD 1: Manual Export (Easiest)"
echo "----------------------------------"
echo "1. Open Firefox and go to: https://www.cochranelibrary.com"
echo "2. Make sure you're logged in (if you have a subscription)"
echo "3. Press F12 to open Developer Tools"
echo "4. Go to 'Storage' tab"
echo "5. Click on 'Cookies' → 'https://www.cochranelibrary.com'"
echo "6. Right-click on the cookie list → 'Copy All'"
echo "7. Save to a text file"
echo ""
echo "METHOD 2: Use cookies.txt extension"
echo "------------------------------------"
echo "1. In Firefox, go to: about:addons"
echo "2. Search for 'cookies.txt'"
echo "3. Install 'cookies.txt' by Lennon Hill"
echo "4. Visit https://www.cochranelibrary.com"
echo "5. Click the extension icon → Export"
echo "6. Save to ~/Downloads/cookies.txt"
echo ""
echo "METHOD 3: Try wget directly (if you're logged in via institution)"
echo "--------------------------------------------------------------------"
echo "If Cochrane Library provides free access via your institution/IP,"
echo "you may not need cookies at all!"
echo ""
echo "Test with:"
echo "wget 'https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD002137.pub3/pdf/full' -O test.pdf"
echo ""
echo "=================================================="
