#!/usr/bin/env python3
"""
Update MCQ Batch - Save Claude Code Generated Content
Updates placeholder MCQs with real clinical content generated by Claude Code
"""

import json
from pathlib import Path
from datetime import datetime


def update_mcq_batch(file_path, generated_mcqs):
    """
    Update MCQ file with generated content

    Args:
        file_path: Path to MCQ JSON file
        generated_mcqs: Dict mapping MCQ ID to generated content
    """
    # Load existing data
    with open(file_path, 'r') as f:
        data = json.load(f)

    updated_count = 0

    # Update MCQs
    for i, mcq in enumerate(data['mcqs']):
        mcq_id = mcq['id']

        if mcq_id in generated_mcqs:
            gen = generated_mcqs[mcq_id]

            # Update question
            mcq['question']['scenario'] = gen['scenario']
            mcq['question']['stem'] = gen['stem']
            mcq['question']['options'] = gen['options']

            # Update answer and explanation
            mcq['correct_answer'] = gen['correct_answer']
            mcq['explanation'] = gen['explanation']

            # Mark as generated
            mcq['generated_by'] = "claude_code"
            mcq['generated_at'] = datetime.now().isoformat()

            updated_count += 1
            print(f"✅ Updated {mcq_id}: {mcq['topic']}")

    # Update metadata
    data['metadata']['claude_code_generated'] = updated_count
    data['metadata']['last_updated'] = datetime.now().isoformat()

    # Save
    with open(file_path, 'w') as f:
        json.dump(data, f, indent=2)

    print(f"\n💾 Saved {updated_count} updated MCQs to {file_path}")
    return updated_count


# Batch 1: ENDO-MCQ-0001 to 0003
batch1_generated = {
    "ENDO-MCQ-0001": {
        "scenario": "A 32-year-old woman presents to her GP with a 3-month history of weight loss (8 kg), palpitations, heat intolerance, and tremor. On examination, her pulse is 110 bpm and regular, she has a fine tremor of outstretched hands, and a smooth, non-tender goitre. Her eyes appear normal with no exophthalmos.",
        "stem": "What is the most appropriate initial investigation to confirm the diagnosis?",
        "options": {
            "A": "Thyroid ultrasound",
            "B": "Thyroid-stimulating hormone (TSH) and free T4 levels",
            "C": "Thyroid autoantibodies (TPO and thyroglobulin)",
            "D": "Radioactive iodine uptake scan"
        },
        "correct_answer": "B",
        "explanation": "The clinical features strongly suggest hyperthyroidism (weight loss, palpitations, tremor, tachycardia, goitre). The most appropriate initial investigation is serum TSH and free T4. In primary hyperthyroidism, TSH will be suppressed (<0.1 mIU/L) and free T4 will be elevated. Thyroid ultrasound and radioactive iodine scans are useful for determining the cause but are not first-line diagnostic tests. Autoantibodies help identify Graves' disease but should follow biochemical confirmation."
    },

    "ENDO-MCQ-0002": {
        "scenario": "A 28-year-old woman is diagnosed with Graves' disease. Her TSH is <0.01 mIU/L, free T4 is 35 pmol/L (reference range 10-20), and TSH receptor antibodies are positive. She is clinically thyrotoxic with a heart rate of 105 bpm. She is not pregnant and wishes to start medical treatment.",
        "stem": "What is the most appropriate initial pharmacological management?",
        "options": {
            "A": "Propylthiouracil 100 mg three times daily",
            "B": "Carbimazole 20-40 mg daily",
            "C": "Radioactive iodine ablation",
            "D": "Propranolol 40 mg twice daily alone"
        },
        "correct_answer": "B",
        "explanation": "Carbimazole is the first-line antithyroid medication in Australia for Graves' disease (Therapeutic Guidelines). Initial dose is typically 20-40 mg daily, titrated according to thyroid function. Propylthiouracil is reserved for first trimester pregnancy or carbimazole intolerance due to higher risk of hepatotoxicity. Radioactive iodine is a definitive treatment but not first-line. Beta-blockers like propranolol provide symptomatic relief but do not treat the underlying hyperthyroidism and should be used as adjunct therapy only."
    },

    "ENDO-MCQ-0003": {
        "scenario": "A 45-year-old woman with known Graves' disease (on carbimazole 20 mg daily for 6 weeks) presents to ED with sudden onset severe sore throat and fever (38.5°C). She started feeling unwell 2 days ago. On examination, she appears septic with pharyngeal erythema but no exudate.",
        "stem": "What is the most important immediate investigation?",
        "options": {
            "A": "Throat swab for bacterial culture",
            "B": "Full blood count (FBC) with differential",
            "C": "Repeat thyroid function tests",
            "D": "Blood cultures"
        },
        "correct_answer": "B",
        "explanation": "This patient has symptoms concerning for agranulocytosis, a rare but serious complication of carbimazole/thionamide therapy (occurs in 0.2-0.5% of patients). Sore throat and fever in a patient on carbimazole is agranulocytosis until proven otherwise. Urgent FBC is essential to check for neutropenia (neutrophils <0.5 × 10⁹/L). If confirmed, carbimazole must be stopped immediately and the patient requires hospital admission, broad-spectrum antibiotics, and haematology input. Patients should be warned about this complication when starting treatment and told to stop medication and seek urgent medical review if sore throat or fever develops."
    }
}


if __name__ == "__main__":
    file_path = "data/mcqs/missing_topics_comprehensive_mcqs.json"

    print("="*70)
    print("MCQ BATCH UPDATE - Claude Code Generated Content")
    print("="*70)
    print(f"Batch 1: ENDO-MCQ-0001 to 0003 (Hyperthyroidism)")
    print("="*70 + "\n")

    updated = update_mcq_batch(file_path, batch1_generated)

    print(f"\n✅ Batch 1 Complete: {updated}/3 MCQs updated")
    print(f"\nNext: Generate Batch 2 (ENDO-MCQ-0004 to 0006)")
