#!/usr/bin/env python3
"""
Regenerate Week 3 Cardiology MCQs - Batch 001-010
Generated by Claude Code (Sonnet 4.5) on 2026-01-27

Constraint compliance:
✅ Constraint 1: Australian medical context, spelling, drug names
✅ Constraint 4.2: Generated by Claude (not local LLMs)
✅ Constraint 12: NO placeholder content - all real clinical scenarios
"""

import json
from pathlib import Path
from datetime import datetime

# Generated MCQ content for WEEK3-CARDIO-001 through WEEK3-CARDIO-010
GENERATED_MCQS = {
    "WEEK3-CARDIO-001": {
        "question": {
            "scenario": "A 62-year-old man presents to the emergency department with sudden onset of severe central chest pain radiating to his left arm and jaw. The pain started 90 minutes ago while he was gardening. He describes it as crushing in nature, 9/10 in severity. He has a history of hypertension and type 2 diabetes mellitus. On examination, he is diaphoretic with BP 145/92 mmHg, HR 98 bpm regular, RR 20/min, SpO2 96% on room air. Heart sounds are normal with no murmurs. Chest is clear. An ECG is performed showing ST-segment elevation of 3mm in leads II, III, and aVF.",
            "stem": "What is the most appropriate immediate diagnosis based on the ECG findings?",
            "options": {
                "A": "Unstable angina",
                "B": "Inferior ST-elevation myocardial infarction (STEMI)",
                "C": "Posterior myocardial infarction",
                "D": "Left ventricular hypertrophy with strain pattern"
            }
        },
        "correct_answer": "B",
        "explanation": "This patient presents with classic features of an acute myocardial infarction. The ECG findings of ST-segment elevation ≥2mm in two or more contiguous leads (II, III, aVF) are diagnostic of STEMI, specifically inferior STEMI given the leads involved. These leads reflect the inferior wall of the left ventricle, typically supplied by the right coronary artery. The clinical presentation of sudden-onset severe chest pain with radiation, diaphoresis, and cardiovascular risk factors (hypertension, diabetes) strongly supports this diagnosis. Option A (unstable angina) is incorrect as it does not produce ST-elevation on ECG. Option C (posterior MI) would show tall R waves in V1-V2 with ST-depression, not ST-elevation in inferior leads. Option D (LVH with strain) typically shows deep S waves in V1-V2 and tall R waves in V5-V6 with ST-depression and T-wave inversion, not acute ST-elevation. Immediate management should include dual antiplatelet therapy (aspirin 300mg and ticagrelor 180mg or clopidogrel 600mg), analgesia, and urgent reperfusion therapy (primary PCI within 90 minutes or thrombolysis if PCI not achievable within 120 minutes)."
    },

    "WEEK3-CARDIO-002": {
        "question": {
            "scenario": "A 58-year-old woman presents to the emergency department with a 3-hour history of central chest tightness occurring at rest. The discomfort is described as pressure-like, 7/10 severity, associated with nausea and shortness of breath. She has a history of hyperlipidaemia and smoking (20 pack-years). Vital signs: BP 138/85 mmHg, HR 92 bpm, RR 18/min, SpO2 98% on room air. ECG shows sinus rhythm with T-wave inversion in leads V3-V5 but no ST-elevation. Initial troponin I is 0.08 ng/mL (normal <0.04 ng/mL). Troponin I repeated at 3 hours is 0.25 ng/mL showing a rising pattern.",
            "stem": "What is the most appropriate diagnosis for this patient?",
            "options": {
                "A": "Unstable angina",
                "B": "Non-ST-elevation myocardial infarction (NSTEMI)",
                "C": "ST-elevation myocardial infarction (STEMI)",
                "D": "Stable angina pectoris"
            }
        },
        "correct_answer": "B",
        "explanation": "This patient has NSTEMI, which is distinguished from unstable angina by the presence of elevated and rising cardiac biomarkers (troponin I rising from 0.08 to 0.25 ng/mL). Both NSTEMI and unstable angina are forms of acute coronary syndrome presenting with chest pain at rest, but NSTEMI involves myocardial necrosis evidenced by troponin elevation, whereas unstable angina does not. The ECG findings of T-wave inversion in precordial leads without ST-elevation support the diagnosis of NSTEMI rather than STEMI. Option A is incorrect because troponin is elevated. Option C is incorrect as there is no ST-elevation ≥1mm in two contiguous leads. Option D (stable angina) is incorrect as the symptoms occur at rest and are associated with troponin elevation, indicating an acute event. According to Australian guidelines (including those referenced in Talley & O'Connor's Clinical Examination), NSTEMI requires risk stratification using GRACE or TIMI scores, dual antiplatelet therapy (aspirin plus ticagrelor or clopidogrel), anticoagulation, and consideration for early invasive management (angiography within 24-72 hours depending on risk). High-intensity statin therapy should also be commenced."
    },

    "WEEK3-CARDIO-003": {
        "question": {
            "scenario": "A 55-year-old man presents to the emergency department with severe central chest pain that started 2 hours ago. He is known to have hypertension and currently takes perindopril. On examination, BP 152/95 mmHg, HR 105 bpm, SpO2 97% on room air. ECG shows ST-depression in leads V4-V6 with T-wave inversion. Initial high-sensitivity troponin T is 18 ng/L (normal <14 ng/L). A repeat troponin T at 1 hour is 45 ng/L. Coronary angiography reveals 80% stenosis of the left anterior descending artery.",
            "stem": "What is the significance of the rising troponin levels in this clinical context?",
            "options": {
                "A": "Rules out acute coronary syndrome",
                "B": "Confirms acute myocardial infarction with ongoing myocardial necrosis",
                "C": "Indicates previous myocardial infarction",
                "D": "Suggests chronic stable coronary artery disease"
            }
        },
        "correct_answer": "B",
        "explanation": "The rising pattern of troponin levels (from 18 ng/L to 45 ng/L) in the context of acute chest pain and ECG changes confirms acute myocardial infarction, specifically NSTEMI given the absence of ST-elevation. A rise and/or fall in troponin with at least one value above the 99th percentile upper reference limit is one of the key diagnostic criteria for acute MI. The magnitude and kinetics of troponin rise reflect ongoing myocardial necrosis. High-sensitivity troponin assays (as used here) allow earlier detection of myocardial injury with improved sensitivity. Option A is incorrect - elevated troponin actually confirms acute coronary syndrome. Option C is incorrect as a previous (old) MI would show elevated but stable or slowly declining troponin levels, not an acute rise. Option D is incorrect as chronic stable CAD without acute event typically has normal troponin. The rising troponin pattern combined with clinical presentation and angiographic findings indicates need for urgent intervention. Australian practice guidelines recommend dual antiplatelet therapy, anticoagulation, high-intensity statin (e.g., atorvastatin 80mg), and consideration for early percutaneous coronary intervention within 24-72 hours based on risk stratification. The significant LAD stenosis (80%) will likely require revascularisation."
    },

    "WEEK3-CARDIO-004": {
        "question": {
            "scenario": "A 67-year-old man is brought to a regional hospital 45 minutes after onset of severe chest pain. ECG shows ST-elevation of 4mm in leads V1-V4 consistent with anterior STEMI. The patient weighs 82kg, BP 135/80 mmHg, HR 95 bpm. He has no contraindications to thrombolysis. The nearest PCI-capable centre is 2 hours away by ambulance. The emergency physician must decide between immediate thrombolysis or transfer for primary PCI.",
            "stem": "What is the most appropriate reperfusion strategy for this patient?",
            "options": {
                "A": "Immediate thrombolysis with tenecteplase followed by transfer",
                "B": "Immediate transfer for primary PCI without thrombolysis",
                "C": "Conservative management with aspirin and clopidogrel only",
                "D": "Wait 2 hours to see if symptoms resolve before deciding"
            }
        },
        "correct_answer": "A",
        "explanation": "In this scenario, the patient presents to a non-PCI-capable hospital within 12 hours of symptom onset. Australian guidelines recommend primary PCI as the preferred reperfusion strategy if it can be performed within 90 minutes of first medical contact. However, if PCI cannot be achieved within this timeframe (as in this case - 2 hours transfer time means total time would exceed 90 minutes), then immediate thrombolysis is indicated, followed by transfer to a PCI-capable centre for rescue PCI if needed or routine angiography within 3-24 hours. Tenecteplase is the preferred thrombolytic agent in Australia, dosed by weight (for 82kg: 45mg IV bolus). Time is critical in STEMI - 'time is myocardium'. Option B is incorrect because the delay to PCI (>90-120 minutes) makes thrombolysis more appropriate. Option C is inadequate as antiplatelet therapy alone does not achieve reperfusion. Option D is dangerous as it delays potentially life-saving reperfusion therapy. After thrombolysis, the patient should receive aspirin 300mg loading dose (then 100-150mg daily), clopidogrel 300mg loading dose (or ticagrelor 180mg), and unfractionated heparin. Beta-blockers and ACE inhibitors should be commenced in the first 24 hours if haemodynamically stable, along with high-intensity statin therapy."
    },

    "WEEK3-CARDIO-005": {
        "question": {
            "scenario": "A 52-year-old woman presents with acute anterior STEMI. She arrives at a PCI-capable tertiary hospital. The cardiac catheterisation laboratory team is immediately activated. Her symptom onset was 75 minutes ago. Current time is 10:15 AM and she has just been taken to the catheterisation laboratory. The interventional cardiologist aims to achieve guideline-recommended door-to-balloon time.",
            "stem": "What is the maximum acceptable door-to-balloon time target for primary PCI in STEMI according to current guidelines?",
            "options": {
                "A": "60 minutes",
                "B": "90 minutes",
                "C": "120 minutes",
                "D": "180 minutes"
            }
        },
        "correct_answer": "B",
        "explanation": "The guideline-recommended door-to-balloon time for primary PCI in STEMI is 90 minutes or less from first medical contact (or hospital arrival) to balloon inflation. This is a key quality metric for STEMI care. In Australia, achieving door-to-balloon times ≤90 minutes is associated with improved outcomes including reduced mortality and infarct size. For patients presenting directly to PCI-capable centres, even more aggressive targets of 60 minutes may be achievable and are encouraged. Option A (60 minutes) represents an optimal target but 90 minutes is the standard guideline recommendation. Option C (120 minutes) is too long for primary PCI at a PCI-capable centre, though it may be acceptable as the maximum time for symptom onset to balloon inflation when including transfer time from a non-PCI centre. Option D (180 minutes) is excessive and associated with worse outcomes. The rationale for the 90-minute target is based on substantial evidence showing that earlier reperfusion saves more myocardium and improves survival. Systems of care should be organised to minimise delays including pre-hospital ECG transmission, direct activation of the catheterisation laboratory bypassing the emergency department when appropriate, and having 24/7 PCI capability. In this case, with symptom onset at 75 minutes ago and immediate catheterisation laboratory activation, the team has a good chance of achieving both symptom onset-to-balloon time <120 minutes and door-to-balloon time <90 minutes."
    },

    "WEEK3-CARDIO-006": {
        "question": {
            "scenario": "A 64-year-old man underwent primary PCI for anterior STEMI 3 days ago with successful stenting of the left anterior descending artery (drug-eluting stent). He is preparing for hospital discharge. His current medications include aspirin 100mg daily, which he has been taking since admission. He has no history of bleeding disorders and his platelet count is 245 × 10⁹/L.",
            "stem": "What is the most appropriate P2Y12 inhibitor and duration for dual antiplatelet therapy (DAPT) post-ACS?",
            "options": {
                "A": "Clopidogrel 75mg daily for 1 month only",
                "B": "Ticagrelor 90mg twice daily for 12 months",
                "C": "Clopidogrel 75mg daily for 6 months only",
                "D": "Prasugrel 5mg daily for 3 months only"
            }
        },
        "correct_answer": "B",
        "explanation": "Following ACS (including STEMI) treated with PCI, current guidelines recommend DAPT with aspirin plus a P2Y12 inhibitor for 12 months, unless there is high bleeding risk. Ticagrelor 90mg twice daily is preferred over clopidogrel in the Australian context for ACS patients, as demonstrated by the PLATO trial showing superior reduction in cardiovascular death, MI, and stroke without significant increase in major bleeding compared to clopidogrel. Ticagrelor should be continued for 12 months post-ACS regardless of stent type. Option A and C are incorrect as clopidogrel, whilst acceptable if ticagrelor is contraindicated or not tolerated, is generally a second-line choice, and the durations of 1 or 6 months are insufficient for post-ACS patients. Option D (prasugrel 5mg) uses an incorrect dose - the standard prasugrel maintenance dose is 10mg daily (5mg is for patients <60kg or age ≥75 years), and 3 months is too short. After 12 months of DAPT, lifelong aspirin monotherapy is typically continued. In some high-risk patients, DAPT may be extended beyond 12 months, whilst in those with very high bleeding risk, shorter durations (3-6 months) may be considered with careful risk-benefit assessment. The combination of aspirin plus ticagrelor provides potent platelet inhibition reducing the risk of stent thrombosis and recurrent ischemic events. Common side effects of ticagrelor include dyspnoea and minor bleeding."
    },

    "WEEK3-CARDIO-007": {
        "question": {
            "scenario": "A 70-year-old man presents to the emergency department with sudden onset central chest pain radiating to both arms, associated with dyspnoea and diaphoresis. His initial ECG shows ST-elevation in the anterior leads. The medical team immediately administers dual antiplatelet therapy as part of initial ACS management. He weighs 75kg and has no history of peptic ulcer disease or bleeding disorders.",
            "stem": "What is the appropriate aspirin loading dose for this patient with acute STEMI?",
            "options": {
                "A": "100mg orally",
                "B": "300mg orally (chewed or dispersed)",
                "C": "600mg orally",
                "D": "75mg orally"
            }
        },
        "correct_answer": "B",
        "explanation": "The recommended aspirin loading dose for acute coronary syndrome (including STEMI) is 300mg, given orally and preferably chewed or dispersed in water for more rapid absorption. This provides immediate antiplatelet effect by irreversibly inhibiting cyclooxygenase-1 (COX-1) in platelets, reducing thromboxane A2 production and platelet aggregation. Option A (100mg) and Option D (75mg) are maintenance doses, not loading doses, and would not achieve rapid therapeutic effect needed in acute STEMI. Option C (600mg) is the loading dose for P2Y12 inhibitors (clopidogrel), not aspirin - whilst not harmful, it provides no additional benefit over 300mg aspirin and this dose is not standard. In Australian practice, aspirin 300mg loading should be given as soon as possible after diagnosis of ACS, ideally in the pre-hospital setting (by paramedics) or immediately upon arrival to hospital. Following the loading dose, maintenance therapy is aspirin 100-150mg daily (typically 100mg in Australia) continued indefinitely unless contraindicated. Aspirin should be given even if the patient is proceeding to primary PCI or thrombolysis. Common adverse effects include gastrointestinal upset and increased bleeding risk. For patients with true aspirin allergy (not just intolerance), clopidogrel or ticagrelor monotherapy may be used, though outcomes are inferior to DAPT. The combination of aspirin plus a P2Y12 inhibitor (clopidogrel, ticagrelor, or prasugrel) forms the cornerstone of antiplatelet therapy in ACS."
    },

    "WEEK3-CARDIO-008": {
        "question": {
            "scenario": "A 59-year-old man with NSTEMI underwent PCI with drug-eluting stent placement 5 days ago. He is being discharged on dual antiplatelet therapy. His cardiologist needs to choose between clopidogrel and ticagrelor for the P2Y12 inhibitor component. The patient has no contraindications to either medication and his eGFR is 68 mL/min/1.73m². He lives 90 minutes from the nearest hospital.",
            "stem": "What is the principal advantage of ticagrelor over clopidogrel in post-ACS management?",
            "options": {
                "A": "Lower cost and once-daily dosing convenience",
                "B": "Superior reduction in cardiovascular death, MI, and stroke",
                "C": "Significantly lower bleeding risk",
                "D": "Does not require dose adjustment in renal impairment"
            }
        },
        "correct_answer": "B",
        "explanation": "Ticagrelor has been shown in the landmark PLATO trial to provide superior reduction in the composite endpoint of cardiovascular death, myocardial infarction, and stroke compared to clopidogrel in ACS patients (9.8% vs 11.7%, p<0.001). This benefit was achieved without a significant increase in major bleeding, making ticagrelor the preferred P2Y12 inhibitor for ACS patients in current guidelines. Unlike clopidogrel which is a prodrug requiring hepatic conversion to its active form (and subject to genetic variability in CYP2C19 metabolism), ticagrelor is a direct-acting, reversible P2Y12 inhibitor providing more consistent and potent platelet inhibition. Option A is incorrect - ticagrelor is typically more expensive than clopidogrel and requires twice-daily dosing (90mg BD) whereas clopidogrel is once daily (75mg), making clopidogrel more convenient and cost-effective. Option C is incorrect - major bleeding rates are similar between ticagrelor and clopidogrel, though ticagrelor may cause more minor bleeding and dyspnoea. Option D is partially correct (ticagrelor doesn't require renal dose adjustment) but this is not its principal advantage; both drugs can be used safely in moderate renal impairment. The main advantage is the improved clinical outcomes. Ticagrelor should be continued for 12 months post-ACS along with aspirin (DAPT), then typically aspirin alone lifelong. Patients should be counselled about the twice-daily dosing requirement and potential side effect of dyspnoea (occurs in ~10-15% of patients but rarely requires discontinuation)."
    },

    "WEEK3-CARDIO-009": {
        "question": {
            "scenario": "A 56-year-old woman underwent successful primary PCI for anterolateral STEMI 36 hours ago. She is haemodynamically stable with BP 118/75 mmHg, HR 78 bpm, no signs of pulmonary oedema. Her echocardiogram shows left ventricular ejection fraction of 42% with anterior wall hypokinesis. She has no history of asthma or COPD. The cardiology team is reviewing her medications before discharge.",
            "stem": "What is the most appropriate beta-blocker management for this patient post-MI?",
            "options": {
                "A": "Avoid beta-blockers due to reduced ejection fraction",
                "B": "Commence beta-blocker (e.g., metoprolol or carvedilol) and continue indefinitely",
                "C": "Commence beta-blocker for 1 month only then discontinue",
                "D": "Beta-blockers are only needed if arrhythmias develop"
            }
        },
        "correct_answer": "B",
        "explanation": "Beta-blockers are a cornerstone of evidence-based post-MI therapy and should be commenced in all patients following myocardial infarction unless contraindicated, and continued indefinitely (not just for a limited period). In this case with reduced LVEF (42%), beta-blockers are particularly important as they provide mortality benefit, reduce risk of sudden cardiac death, decrease reinfarction rates, and improve left ventricular remodelling. Cardioselective beta-1 selective agents such as metoprolol (target dose 47.5-95mg BD) or bisoprolol (target dose 10mg daily) are commonly used. Carvedilol (target dose 25mg BD) is also an option with additional alpha-blocking properties. Beta-blockers should be initiated early (within 24 hours) once the patient is haemodynamically stable and titrated to maximum tolerated dose targeting resting heart rate of 55-60 bpm. Option A is incorrect - reduced LVEF is actually an indication for beta-blocker therapy, not a contraindication. Absolute contraindications include cardiogenic shock, decompensated heart failure, severe bradycardia, and high-degree AV block. Option C is incorrect - the benefit of beta-blockers extends well beyond 1 month; they should be continued indefinitely unless side effects or contraindications develop. Historical recommendations suggested minimum 2-3 years, but current practice is lifelong therapy. Option D is incorrect - beta-blockers are indicated for all post-MI patients regardless of arrhythmia status, though they do also help prevent ventricular arrhythmias. Common side effects include fatigue, bradycardia, hypotension, and erectile dysfunction, which may require dose adjustment but rarely necessitate discontinuation."
    },

    "WEEK3-CARDIO-010": {
        "question": {
            "scenario": "A 68-year-old man is recovering from inferior STEMI treated with primary PCI 48 hours ago. His initial blood pressure was 145/90 mmHg but is now 128/78 mmHg after initial management. Echocardiography shows LVEF 45% with inferior wall hypokinesis. Serum creatinine is 98 μmol/L (baseline 92 μmol/L), potassium 4.2 mmol/L. He has no history of renal artery stenosis or severe aortic stenosis. His current medications include aspirin, ticagrelor, atorvastatin, and metoprolol.",
            "stem": "When should ACE inhibitor therapy be commenced in this post-MI patient?",
            "options": {
                "A": "Wait 6 months to ensure haemodynamic stability",
                "B": "Within the first 24 hours if haemodynamically stable",
                "C": "Only if heart failure symptoms develop",
                "D": "ACE inhibitors are contraindicated post-MI"
            }
        },
        "correct_answer": "B",
        "explanation": "ACE inhibitors should be commenced within the first 24 hours following myocardial infarction in haemodynamically stable patients, particularly those with anterior MI, reduced LVEF (<40-50%), or clinical heart failure. In this patient with inferior STEMI and LVEF 45%, early ACE inhibitor therapy is strongly indicated. Large trials (including SAVE, AIRE, TRACE) have demonstrated that ACE inhibitors reduce mortality, reinfarction, and development of heart failure post-MI through beneficial effects on ventricular remodelling, reduction in preload and afterload, and neurohormonal modulation. Perindopril (initial dose 2-4mg daily, target 8-10mg daily) or ramipril (initial dose 2.5mg daily, target 10mg daily) are commonly used in Australia. Therapy should be initiated at low doses and titrated upward over several weeks as tolerated. Option A is incorrect - waiting 6 months misses the critical period for preventing adverse ventricular remodelling; early initiation (within 24 hours) is crucial. Option C is incorrect - ACE inhibitors are indicated for all post-MI patients with LVEF ≤40% or heart failure, anterior MI, or diabetes, not just when symptoms develop; prophylactic use improves outcomes. Option D is incorrect - ACE inhibitors are a Class I recommendation post-MI. Contraindications include bilateral renal artery stenosis, pregnancy, angioedema, and severe hypotension. Close monitoring of renal function (creatinine, potassium) is required, particularly in the first few weeks. If ACE inhibitors are not tolerated (e.g., due to cough), angiotensin receptor blockers (ARBs) such as candesartan or valsartan are alternatives, though ACE inhibitors are preferred if tolerated. The combination with beta-blockers, statins, and antiplatelet therapy forms comprehensive evidence-based post-MI pharmacotherapy."
    }
}

def main():
    """Update MCQs 001-010 with generated content"""
    input_file = Path("data/mcqs/week3_cardiology_200_mcqs.json")

    print("Loading MCQs...")
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    updated_count = 0

    for mcq in data['mcqs']:
        mcq_id = mcq['id']

        if mcq_id in GENERATED_MCQS:
            mcq['question'] = GENERATED_MCQS[mcq_id]['question']
            mcq['correct_answer'] = GENERATED_MCQS[mcq_id]['correct_answer']
            mcq['explanation'] = GENERATED_MCQS[mcq_id]['explanation']
            mcq['regeneration_failed'] = False
            mcq['regenerated_at'] = datetime.now().isoformat()
            mcq['regenerated_by'] = "Claude Code (Sonnet 4.5)"
            updated_count += 1
            print(f"✅ Updated {mcq_id}: {mcq['subtopic']}")

    # Update metadata
    data['metadata']['regeneration_date'] = datetime.now().isoformat()
    data['metadata']['regenerated_batch'] = "001-010"
    data['metadata']['llm_model'] = "Claude Code (Sonnet 4.5)"

    # Save
    with open(input_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"\n✅ Successfully updated {updated_count} MCQs")
    print(f"📝 Saved to {input_file}")
    print(f"\n📊 Progress: 10/200 MCQs regenerated (5%)")

if __name__ == "__main__":
    main()
