#!/usr/bin/env python3
"""
MED-003: Gastroenterology & Hepatology Expert
Gastroenterology specialist for AMC exam preparation

Generated by: scripts/generate_medical_agents.py
"""

from typing import Dict, List, Any
from agents.medical.base_medical_expert import BaseMedicalExpert
from agents.base_agent import AgentMetadata, AgentRole


class GastroenterologyExpert(BaseMedicalExpert):
    """
    MED-003: Gastroenterology & Hepatology Expert

    Australian guideline compliance:
    - Therapeutic Guidelines: Gastroenterology (eTG Section 4.x)
    - Therapeutic Guidelines: Gastrointestinal
    """

    def __init__(self, rag_system=None):
        """Initialize Gastroenterology Expert Agent"""
        metadata = AgentMetadata(
            agent_id="MED-003",
            name="Gastroenterology & Hepatology Expert",
            role=AgentRole.MEDICAL_EXPERT,
            experience_years=15,
            technologies=['Therapeutic Guidelines: Gastrointestinal', 'Gastroenterological Society of Australia (GESA) guidelines', "Crohn's and Colitis Australia guidelines"],
            specializations=['Upper GI bleeding', 'Lower GI bleeding', 'Inflammatory bowel disease', 'GORD and peptic ulcer disease', 'Acute abdomen and surgical emergencies'],
            pros=[
                "Expert in Australian gastroenterology guidelines",
                "15+ years clinical experience",
                "AMC Clinical Exam preparation specialist",
                "Evidence-graded recommendations (GRADE system)"
            ],
            cons=[
                "Limited to gastroenterology domain",
                "Requires validation for complex cases"
            ],
            max_concurrent_tasks=5,
            quality_gate_required=True,
            version="2.0.0"
        )

        super().__init__(metadata, rag_system)
        self._register_gastroenterology_tools()

    def _get_specialty_sources(self) -> List[str]:
        """Return primary sources for gastroenterology"""
        return ['Therapeutic Guidelines: Gastrointestinal', 'Gastroenterological Society of Australia (GESA) guidelines', "Crohn's and Colitis Australia guidelines"]

    def _get_specialty_topics(self) -> List[str]:
        """Return high-yield gastroenterology topics for AMC"""
        return ['Upper GI bleeding (UGIB)', 'Lower GI bleeding (LGIB)', "Inflammatory bowel disease (IBD - Crohn's, UC)", 'GORD and peptic ulcer disease', 'Acute abdomen and surgical emergencies', 'Hepatitis (A, B, C)', 'Cirrhosis and chronic liver disease', 'Coeliac disease', 'Pancreatitis (acute and chronic)', 'Colorectal cancer screening']

    def _register_gastroenterology_tools(self):
        """Register gastroenterology-specific tools"""
        self.register_tool("glasgow_blatchford_score", self._glasgow_blatchford_score, "Calculate Glasgow-Blatchford score for UGIB")
        self.register_tool("rockall_score", self._rockall_score, "Calculate Rockall score for UGIB risk")
        self.register_tool("assess_abdominal_pain", self._assess_abdominal_pain, "Systematic abdominal pain assessment")
        self.register_tool("assess_gi_bleeding", self._assess_gi_bleeding, "GI bleeding assessment and management")

    def _glasgow_blatchford_score(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Calculate Glasgow-Blatchford score for UGIB

        Implementation pending - integrate with RAG system
        """
        self.logger.info(f"Executing glasgow_blatchford_score...")
        return {"status": "success", "message": "Tool implementation pending"}

    def _rockall_score(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Calculate Rockall score for UGIB risk

        Implementation pending - integrate with RAG system
        """
        self.logger.info(f"Executing rockall_score...")
        return {"status": "success", "message": "Tool implementation pending"}

    def _assess_abdominal_pain(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Systematic abdominal pain assessment

        Implementation pending - integrate with RAG system
        """
        self.logger.info(f"Executing assess_abdominal_pain...")
        return {"status": "success", "message": "Tool implementation pending"}

    def _assess_gi_bleeding(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        GI bleeding assessment and management

        Implementation pending - integrate with RAG system
        """
        self.logger.info(f"Executing assess_gi_bleeding...")
        return {"status": "success", "message": "Tool implementation pending"}


def main():
    """Test the Gastroenterology Expert Agent"""
    print("="*80)
    print("MED-003: Gastroenterology & Hepatology Expert Test")
    print("="*80)

    agent = GastroenterologyExpert()
    print(f"Agent ID: {agent.metadata.agent_id}")
    print(f"Specializations: {', '.join(agent.metadata.specializations)}")
    print("✅ Agent initialized successfully")


if __name__ == "__main__":
    main()
